### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by zuurw** [Beowulf59000/skill-my-barista#1]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by Beowulf59000** [comment]
Hello Zuur!
Thanks for your proposal ! It would be awesome, and you have made some great works in other repositories :)

But unfortunately here's some facts : 
- As you can see it is currently an 'alpha', because I developed it during an ASK french event and I try to clean code and make more tests in it before adding new features (for example, it's only in french right now...). 
- Because of this 'alpha version' I can't tell you when it will be released and available on Alexa Store (I hope to finish my first version at the end of August) and when your work will be also visible : so if you want to collaborate and also have multiple projects, do not prioritize my repository).

So, it's your choice :) and thanks for your interest!

Regards, 
Johnny

**Comment by zuurw** [comment]
Hi @Beowulf59000,
That´s not a problem for me, I can do it the logo and when you release it you can show me how it looks :)
I just ask you to put the logo on the README.md file of this project.

So for the logo concept do you have something in your mind? can you tell me more about this project? I just need something to get inspired.

Best Regards!

**Comment by Beowulf59000** [comment]
Hi @zuurw, 

Okay :) Yes of course your the logo will be on the README.md file.
For this project I will need a small icon (108x108 pixel PNG or JPG) and a large icon (512x512 pixel PNG or JPG). You can also do another large icon for the README if you want to :)

I will update the README.md file soon to explain more about the project, but it's all about have some coffee recipes (Latte, Machiatto, Expresso, etc.) in one Amazon Alexa Skill, with a good user interaction and some suggestions about it. So any Alexa devices will be able to suggest us a recipe, tell us the ingredients to prepare and send us the recipe on our smartphone : it will be like a "barista teacher". 

I supposed you guessed, It could be great if the logo represents  a coffee bean or a coffee cup :)

I also renamed the repository because the name was not representative of the Skill name.

Best regards :)

**Comment by zuurw** [comment]
Hi @Beowulf59000 
Thanks for the informations, I will start to design today.

Best Regards!

**Comment by zuurw** [comment]
Hello @Beowulf59000  here are my designs for your logo, for the concept I decided to use a chef's hat as a reference to recipes, so the first concept is a coffee bean with a chef's hat, the second is a cup of coffee with a chef hat drawn in the cream, finally the last one is a coffee cup with the several layers that constitute a capucino with a hat of chef in the top.

I also put the logos with text and create a app button for all of them.

I hope you like one of this.

Best regards!
![coffe proposal](https://user-images.githubusercontent.com/40801473/42876883-f52c32b2-8a7f-11e8-80e3-342421c4687b.png)

**Comment by Beowulf59000** [comment]
Hello @zuurw, 

Wow, great job!

- First version : the coffee bean was finally a bad idea, i'm sorry : even if it's good, a coffee app is more explicit with a cup logo than a bean logo.
- Second version : I like it, but we don't see the cup enough :( 
- Third version : I love it! This layers idea is awesome, I love this logo, we can see the cup, the layer the hat which can also be interpreted as steam from a steam nozzle. I think I'll use it :) 
If you could also just write "My Barista" : I prefix my projects with "skill" to identify it as an Alexa Skill, but the published name on the store will be "My Barista".

Great job again, you have done an awesome job.
If you want, you can create a feature branch from master branch to put your files when you have done :)

Best Regards!

**Comment by Beowulf59000** [comment]
Hello @zuurw,
For your information, don’t worry if you find many deleted files in this repository : I splitted the code in another repo 🙂

**Comment by zuurw** [comment]
Hi @Beowulf59000 sorry that I didnt send you the files, Im going to make the PR today.

Best Regards!

**Comment by zuurw** [comment]
Hi @Beowulf59000 I create the PR, see if everything is good.

**Comment by Beowulf59000** [comment]
Hi @zuurw, no problem, I notified you in case you wondered if I abandoned the project, not to make you in a hurry ;)

I validate your PR, thanks a lot and great job again!

Best regards :)

**Comment by zuurw** [comment]
Thank you @Beowulf59000 !

If you need something just say it, Im here to help.

Best Regards!
